<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static findOrFail(int $int)
 * @method static latest()
 * @method static create(array $array)
 */
class Brand extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'web_url',
        'description',
        'status',
        'created_by',
        'updated_by',
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Admin::class, 'updated_by');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Brand $brand) {
            $brand->slug = slug($brand->name);
            $brand->created_by = Auth::id() ?? 1;
            $brand->updated_by = Auth::id() ?? 1;
        });

        self::updating(function (Brand $brand) {
            $brand->slug = slug($brand->name);
            $brand->updated_by = Auth::id();
        });
    }
}
