<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Class Offer
 * @mixin Eloquent
 */
class Offer extends Model
{
    use HasFactory;

    const OFFER_TYPE = [
        1 => 'Percentages',
        2 => 'Dollar',
    ];


    protected $fillable = [
        'product_id',
        'title',
        'slug',
        'type',
        'amount',
        'status',
        'start_at',
        'expire_at',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'start_at' => 'datetime',
        'expire_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($social) {
            $social->slug = slug($social->title);
            $social->created_by = Auth::id() ?? 1;
            $social->updated_by = Auth::id() ?? 1;
        });
        static::updating(function ($social) {
            $social->slug = slug($social->title);
            $social->updated_by = Auth::id();
        });
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function users(){
        return $this->belongsToMany(User::class);
    }

}
