<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class ShippingMethod extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'applicable_amount',
        'charge',
        'status',
        'created_by',
        'updated_by',
    ];

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Admin::class, 'updated_by');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (ShippingMethod $shippingMethod) {
            $shippingMethod->slug = slug($shippingMethod->name);
            $shippingMethod->created_by = Auth::id() ?? 1;
            $shippingMethod->updated_by = Auth::id() ?? 1;
        });

        self::updating(function (ShippingMethod $shippingMethod) {
            $shippingMethod->slug = slug($shippingMethod->name);
            $shippingMethod->updated_by = Auth::id();
        });
    }

    public function scopeActive($query){
        return $query->where('status', 1);
    }
}
