<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static latest()
 */
class Tax extends Model
{
    use HasFactory;

    const TAX_TYPE = [
        1 => 'Percentages',
        2 => 'Dollar',
    ];


    protected $fillable = [
        'name',
        'slug',
        'type',
        'tax',
        'status',
        'created_by',
        'updated_by',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($tax) {
            $tax->slug = slug($tax->name);
            $tax->created_by = Auth::id() ?? 1;
            $tax->updated_by = Auth::id() ?? 1;
        });
        static::updating(function ($tax) {
            $tax->slug = slug($tax->name);
            $tax->updated_by = Auth::id();
        });
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}
